/**
 * POST /api/agents/goal-generator
 *
 * Streaming goal-generator agent endpoint.
 * Body: { sphereId: string; message: string; phase: DialogPhase }
 * Returns: ReadableStream (Vercel AI SDK streamText protocol)
 */
import { streamText, generateText, stepCountIs } from 'ai'
import { z } from 'zod'
import { NextResponse, type NextRequest } from 'next/server'
import { getSmartModel } from '@/lib/ai/provider'
import { createClient } from '@/lib/supabase/server'
import { listNotesByPrefix } from '@/lib/supabase/notes'
import { getGoalsByUser, saveDialogMessage, getDialogMessages, clearDialogMessages, getActiveGoalBySphere } from '@/lib/supabase/goals'
import { getSphereById, getActivityPeriodForSphere } from '@/lib/supabase/spheres'
import { buildContextMessages } from '@/lib/agents/goal-generator/context'
import {
  GOAL_GENERATOR_SYSTEM_PROMPT,
  buildContextInjection,
} from '@/lib/agents/goal-generator/prompt'
import { createGoalGeneratorTools } from '@/lib/agents/goal-generator/tools'
import type { DialogPhase } from '@/lib/supabase/types'
import { createLogger } from '@/lib/logger'

const logger = createLogger('agents/goal-generator')

export async function POST(request: NextRequest) {
  let userId: string | undefined
  let sphereId: string | undefined

  try {
    const body = await request.json() as {
      sphereId: string
      message: string
      phase?: DialogPhase
      forceGenerate?: boolean
      forceToolName?: string
      materials?: Array<{ url: string; title?: string }>
    }
    sphereId = body.sphereId
    const userMessage: string = body.message
    const phase: DialogPhase = body.phase ?? 'gathering'
    const forceGenerate: boolean = body.forceGenerate ?? false
    const forceToolName: string | undefined = body.forceToolName

    logger.debug('goal-generator request', {
      sphereId,
      phase,
      messageLength: userMessage?.length ?? 0,
      forceGenerate,
      forceToolName,
      hasMaterials: !!body.materials?.length,
    })

    if (!sphereId || !userMessage) {
      return NextResponse.json({ error: 'sphereId and message are required' }, { status: 400 })
    }

    // 1. Auth check
    const supabase = await createClient()
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      logger.warn('goal-generator: unauthenticated request')
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    userId = user.id

    // 2. Load sphere info
    const sphere = await getSphereById(supabase, sphereId)
    if (!sphere || sphere.user_id !== userId) {
      logger.warn('goal-generator: sphere not found or not owned', { userId, sphereId })
      return NextResponse.json({ error: 'Sphere not found' }, { status: 404 })
    }

    // 3. Load @me profile notes for context
    const meNotes = await listNotesByPrefix(supabase, userId, '@me/')
    const userProfile = meNotes
      .map(n => `### ${n.title}\n${n.content}`)
      .join('\n\n')

    logger.debug('context built', {
      profileNoteCount: meNotes.length,
      profileLength: userProfile.length,
    })

    // 4. Load activity period for feasibility tool
    const activityPeriod = await getActivityPeriodForSphere(supabase, userId, sphereId)
    if (!activityPeriod) {
      logger.warn('goal-generator: sphere has no activity period — feasibility tool unavailable', { sphereId })
    }

    // 5. Load active goals count + per-sphere constraint check
    const activeGoals = await getGoalsByUser(supabase, userId, 'active')
    const activeGoalsCount = activeGoals.length
    const activeGoalInSphere = await getActiveGoalBySphere(supabase, userId, sphereId)
    const hasActiveGoalInSphere = !!activeGoalInSphere

    logger.debug('goal-generator route', {
      sphereId,
      phase,
      hasMaterials: !!body.materials?.length,
      hasActivityPeriod: !!activityPeriod,
    })
    logger.debug('sphere active goal check', { sphereId, hasActiveGoalInSphere, existingGoalId: activeGoalInSphere?.id ?? null })

    // 6. Build context messages (with rolling summary if needed)
    // [FIX] Fallback to empty context on network failure so the user can still chat
    let contextMessages: Awaited<ReturnType<typeof buildContextMessages>> = []
    try {
      contextMessages = await buildContextMessages(
        supabase,
        userId,
        sphereId,
        userProfile,
        `User has ${activeGoalsCount} active goal(s).`,
        false  // calendar no longer used in v2 prompt
      )
    } catch (ctxErr) {
      const msg = ctxErr instanceof Error ? ctxErr.message : String(ctxErr)
      logger.error('[FIX] buildContextMessages failed — continuing with empty context', { userId, sphereId, error: msg })
      // Swallow all context errors — losing history is always better than a 500
    }

    // 7. Save the new user message to DB
    // Skip internal trigger messages (generated by buttons, not typed by user)
    const isInternalTrigger = forceGenerate
    if (isInternalTrigger) {
      logger.debug('[FIX] Skipping DB save for internal trigger message', { forceToolName })
    } else {
      await saveDialogMessage(supabase, {
        user_id: userId,
        sphere_id: sphereId,
        role: 'user',
        content: userMessage,
        phase,
      })
    }

    // 8. Build full messages array: context + new user message
    const messages = [
      ...contextMessages,
      { role: 'user' as const, content: userMessage },
    ]

    const contextInjection = buildContextInjection({
      userProfile,
      activeGoalsCount,
      sphereName: sphere.name,
      activityPeriod,
      hasActiveGoalInSphere,
    })

    // Build tools bound to the sphere's activity period
    const tools = createGoalGeneratorTools(activityPeriod)

    const systemPrompt = GOAL_GENERATOR_SYSTEM_PROMPT + '\n' + contextInjection

    // For button-triggered forced tool calls use generateText (non-streaming).
    // This avoids the @ai-sdk/anthropic@3.0.46 parallel-tool streaming bug:
    // with toolChoice 'required' the model calls BOTH readyToGenerateQuests AND
    // generateQuests simultaneously, and neither tool-input stream ever completes.
    // generateText has no streaming, so the bug does not apply.
    if (forceGenerate && forceToolName) {
      logger.info('[FIX] generateText forced tool call', { forceToolName, messageCount: messages.length })

      // Retry once on transient "Invalid JSON response" (Anthropic API overload / rate limit returns non-JSON body)
      let genResult: Awaited<ReturnType<typeof generateText>>
      try {
        genResult = await generateText({
          model: getSmartModel(),
          system: systemPrompt,
          messages,
          tools,
          maxOutputTokens: 16000,
          toolChoice: { type: 'tool' as const, toolName: forceToolName as keyof typeof tools },
        })
      } catch (firstErr) {
        const firstMsg = firstErr instanceof Error ? firstErr.message : String(firstErr)
        const e = firstErr as Record<string, unknown>
        logger.warn('[FIX] generateText first attempt failed, retrying', {
          forceToolName,
          error: firstMsg,
          errorName: firstErr instanceof Error ? firstErr.name : typeof firstErr,
          statusCode: e?.statusCode,
          responseBody: typeof e?.responseBody === 'string' ? e.responseBody.slice(0, 500) : e?.responseBody,
          stack: firstErr instanceof Error ? firstErr.stack?.split('\n').slice(0, 4).join(' | ') : undefined,
        })
        genResult = await generateText({
          model: getSmartModel(),
          system: systemPrompt,
          messages,
          tools,
          maxOutputTokens: 16000,
          toolChoice: { type: 'tool' as const, toolName: forceToolName as keyof typeof tools },
        })
      }

      logger.info('[FIX] generateText result', {
        finishReason: genResult.finishReason,
        toolCallCount: genResult.toolCalls?.length ?? 0,
        toolResultCount: genResult.toolResults?.length ?? 0,
        toolCallNames: genResult.toolCalls?.map((tc: { toolName: string }) => tc.toolName) ?? [],
      })

      // AI SDK v6: TypedToolResult uses 'output' (not 'result')
      let toolResult = (genResult.toolResults as Array<{ output: unknown }>)[0]?.output

      // [FIX] AI SDK v6: toolResults is empty because executeToolCall() cannot find
      // tool.execute via its internal lookup. Fall back to calling execute() directly.
      // IMPORTANT: TypeScript type says .args but the runtime tool-call object stores
      // the validated arguments in .input (see asContent / parseToolCall in SDK source).
      if (toolResult == null && genResult.toolCalls.length > 0) {
        const rawCall = genResult.toolCalls[0] as unknown as { toolName: string; input?: unknown; args?: unknown }
        const toolInput = rawCall.input ?? rawCall.args
        logger.warn('[FIX] toolResults empty — manually invoking execute()', {
          calledToolName: rawCall.toolName,
          expectedToolName: forceToolName,
          hasInput: toolInput != null,
        })
        const tool = tools[rawCall.toolName as keyof typeof tools]
          ?? tools[forceToolName as keyof typeof tools]
        if (tool?.execute && toolInput != null) {
          toolResult = await tool.execute(toolInput as never, undefined as never)
        }
      }

      if (toolResult == null) {
        logger.error('[FIX] generateText: no tool result', { forceToolName, finishReason: genResult.finishReason })
        return NextResponse.json({ error: 'Tool did not return a result' }, { status: 500 })
      }

      return NextResponse.json({ toolResult })
    }

    logger.info('[FIX] streaming started', {
      userId,
      sphereId,
      messageCount: messages.length,
      forceGenerate,
      forceToolName,
    })

    // 9. Stream with configured provider (anthropic or openrouter) + tools
    const result = streamText({
      model: getSmartModel(),
      system: systemPrompt,
      messages,
      tools,
      toolChoice: 'auto',
      stopWhen: stepCountIs(5),
      onFinish: async ({ text, usage }) => {
        logger.info('streaming finished', {
          userId,
          sphereId,
          totalTokens: usage?.totalTokens,
          textLength: text?.length,
        })

        // 10. Save assistant message to DB
        if (text) {
          try {
            await saveDialogMessage(supabase, {
              user_id: userId!,
              sphere_id: sphereId!,
              role: 'assistant',
              content: text,
              phase,
            })
          } catch (saveErr) {
            logger.error('failed to save assistant message', {
              userId,
              sphereId,
              error: saveErr instanceof Error ? saveErr.message : String(saveErr),
            })
          }
        }
      },
    })

    return result.toUIMessageStreamResponse()

  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error)
    const e = error as Record<string, unknown>
    logger.error('streaming failed', {
      userId,
      sphereId,
      error: errorMessage,
      errorName: error instanceof Error ? error.name : typeof error,
      statusCode: e?.statusCode,
      responseBody: typeof e?.responseBody === 'string' ? e.responseBody.slice(0, 500) : e?.responseBody,
      stack: error instanceof Error ? error.stack?.split('\n').slice(0, 5).join(' | ') : undefined,
    })
    return NextResponse.json(
      { error: process.env.NODE_ENV === 'development' ? errorMessage : 'Internal server error' },
      { status: 500 }
    )
  }
}

/**
 * GET /api/agents/goal-generator?sphereId=...
 * Load existing dialog messages for resuming a session.
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const sphereId = searchParams.get('sphereId')

    if (!sphereId) {
      return NextResponse.json({ error: 'sphereId is required' }, { status: 400 })
    }

    const supabase = await createClient()
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    logger.debug('goal-generator GET', { userId: user.id, sphereId })

    const messages = await getDialogMessages(supabase, user.id, sphereId)

    logger.debug('goal-generator GET result', { userId: user.id, sphereId, count: messages.length })

    return NextResponse.json({ messages })

  } catch (error) {
    logger.error('goal-generator GET failed', {
      error: error instanceof Error ? error.message : String(error),
    })
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

/**
 * DELETE /api/agents/goal-generator?sphereId=...
 * Clear all dialog messages for a sphere (called on dialog close to prevent stale messages on next open).
 */
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const sphereId = searchParams.get('sphereId')

    if (!sphereId) {
      return NextResponse.json({ error: 'sphereId is required' }, { status: 400 })
    }

    const supabase = await createClient()
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    logger.debug('[FIX] goal-generator DELETE: clearing dialog messages', { userId: user.id, sphereId })

    await clearDialogMessages(supabase, user.id, sphereId)

    logger.debug('[FIX] goal-generator DELETE: done', { userId: user.id, sphereId })

    return NextResponse.json({ ok: true })

  } catch (error) {
    logger.error('goal-generator DELETE failed', {
      error: error instanceof Error ? error.message : String(error),
    })
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
