-- Migration 015: KB Chat Sessions
-- Persistent, session-based chat for the Knowledge Base RAG panel.
-- Sessions are user-level only (no binding to notes/tags/goals).
-- Supports context compression via is_compressed_summary flag.

-- Session container (one per conversation thread)
CREATE TABLE kb_chat_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT,  -- null until auto-generated by haiku after first exchange
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_message_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ON kb_chat_sessions(user_id, last_message_at DESC);
ALTER TABLE kb_chat_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own kb sessions" ON kb_chat_sessions
  FOR ALL USING (user_id = auth.uid());

-- Messages within a session
CREATE TABLE kb_chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES kb_chat_sessions(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  is_compressed_summary BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ON kb_chat_messages(session_id, created_at ASC);
ALTER TABLE kb_chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users own kb messages" ON kb_chat_messages
  FOR ALL USING (user_id = auth.uid());
